---
- name: install and start httpd
  hosts: web

  tasks:
    - name: verify httpd is present
      yum: 
        name: httpd
        state: present

    - name: copy index
      copy: 
        src: files/index.html
        dest: /var/www/html/index.html

    - name: httpd is started
      service:
        name: httpd
        state: started
        enabled: true  
