---
- name: Restart env only if a key config file was updated
  hosts: all

  tasks:
    - name: Update apache config file
      copy:
        src: templates/httpd.conf
        dest: /etc/httpd/conf/httpd.conf

    - name: Update mysql config file
      copy:
        src: templates/my.cnf
        dest: /etc/my.cnf

      notify:
        - restart_apache 
        - restart_mysql

  handlers:
    - name: restart_apache
      service:
        name: httpd
        state: restarted


    - name: restart_mysql
      service:
        name: mariadb
        state: restarted

